# Generated by Django 4.2.7 on 2023-12-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("toys_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="length",
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="stripe",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="stripe_text",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(max_length=2000),
        ),
    ]
