# Generated by Django 4.2.7 on 2023-12-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("toys_app", "0003_alter_product_length_alter_product_stripe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="length",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
