# Generated by Django 4.2.7 on 2023-12-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("toys_app", "0006_remove_product_stripe_remove_product_stripe_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="delivery",
            field=models.CharField(default="delivery", max_length=1000),
        ),
    ]
