# Generated by Django 4.2.7 on 2023-12-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("toys_app", "0007_product_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="total_cost",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
